# Generated by Django 4.0.3 on 2022-03-15 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('cases', models.FloatField(default=0, help_text='Number of cases')),
                ('todayCases', models.FloatField(default=0, help_text='Number of Today cases')),
                ('deaths', models.FloatField(default=0, help_text='Number of deaths')),
                ('todayDeaths', models.FloatField(default=0, help_text='Number of Today Deths')),
                ('recovered', models.FloatField(default=0, help_text='Number of recovery cases')),
                ('active', models.FloatField(default=0, help_text='Number of active cases')),
                ('critical', models.FloatField(default=0, help_text='Number of criticle cases')),
                ('casesPerOneMillion', models.FloatField(default=0)),
                ('deathsPerOneMillion', models.FloatField(default=0)),
                ('totalTests', models.FloatField(default=0, help_text='Number of total test')),
                ('testsPerOneMillion', models.FloatField(default=0)),
            ],
        ),
    ]
